## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_to_load = "WeatherPy_Database.csv"

city_data_df = pd.read_csv(city_data_to_load)
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Barcarena,BR,-1.5058,-48.6258,75.25,90,100,9.91,heavy intensity rain
1,1,Ulladulla,AU,-35.3500,150.4667,49.77,83,65,8.14,broken clouds
2,2,Dingle,PH,10.9995,122.6711,78.12,87,100,8.19,overcast clouds
3,3,Potsdam,DE,52.3989,13.0657,61.34,40,9,5.30,clear sky
4,4,Fairbanks,US,64.8378,-147.7164,42.22,69,75,11.50,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 20
What is the maximum temperature you would like for your trip? 100

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Barcarena,BR,-1.5058,-48.6258,75.25,90,100,9.91,heavy intensity rain
1,1,Ulladulla,AU,-35.3500,150.4667,49.77,83,65,8.14,broken clouds
2,2,Dingle,PH,10.9995,122.6711,78.12,87,100,8.19,overcast clouds
3,3,Potsdam,DE,52.3989,13.0657,61.34,40,9,5.30,clear sky
4,4,Fairbanks,US,64.8378,-147.7164,42.22,69,75,11.50,broken clouds
5,5,Lagoa,PT,39.0500,-27.9833,61.84,77,48,10.94,scattered clouds
6,6,Acarau,BR,-2.8856,-40.1200,79.81,85,100,11.65,moderate rain
7,7,Heishan,CN,41.6892,122.1128,48.63,46,0,4.50,clear sky
8,8,Rikitea,PF,-23.1203,-134.9692,76.60,76,88,21.23,overcast clouds
9,9,Hof,DE,50.3167,11.9167,56.44,72,28,6.91,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                2388
City                   2388
Country                2373
Lat                    2388
Lng                    2388
Max Temp               2388
Humidity               2388
Cloudiness             2388
Wind Speed             2388
Current Description    2388
dtype: int64

In [6]:
preferred_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2388 entries, 0 to 2417
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              2388 non-null   int64
 1   City                 2388 non-null   object
 2   Country              2373 non-null   object
 3   Lat                  2388 non-null   float64
 4   Lng                  2388 non-null   float64
 5   Max Temp             2388 non-null   float64
 6   Humidity             2388 non-null   int64
 7   Cloudiness           2388 non-null   int64
 8   Wind Speed           2388 non-null   float64
 9   Current Description  2388 non-null   object
dtypes: float64(4), int64(3), object(3)
memory usage: 205.2+ KB

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Barcarena,BR,-1.5058,-48.6258,75.25,90,100,9.91,heavy intensity rain
1,1,Ulladulla,AU,-35.3500,150.4667,49.77,83,65,8.14,broken clouds
2,2,Dingle,PH,10.9995,122.6711,78.12,87,100,8.19,overcast clouds
3,3,Potsdam,DE,52.3989,13.0657,61.34,40,9,5.30,clear sky
4,4,Fairbanks,US,64.8378,-147.7164,42.22,69,75,11.50,broken clouds
...,...,...,...,...,...,...,...,...,...,...
2413,2413,Salvador,SV,13.8333,-88.9167,84.24,59,91,5.08,overcast clouds
2414,2414,Holland,US,42.7875,-86.1089,69.49,43,0,4.61,clear sky
2415,2415,Hagerstown,US,39.6418,-77.7200,61.68,41,20,0.00,few clouds
2416,2416,Jha Jha,IN,24.7667,86.3667,85.33,52,48,12.53,scattered clouds
2417,2417,Fasa,IR,28.9383,53.6482,67.24,22,0,4.61,clear sky

In [8]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2373 entries, 0 to 2417
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              2373 non-null   int64
 1   City                 2373 non-null   object
 2   Country              2373 non-null   object
 3   Lat                  2373 non-null   float64
 4   Lng                  2373 non-null   float64
 5   Max Temp             2373 non-null   float64
 6   Humidity             2373 non-null   int64
 7   Cloudiness           2373 non-null   int64
 8   Wind Speed           2373 non-null   float64
 9   Current Description  2373 non-null   object
dtypes: float64(4), int64(3), object(3)
memory usage: 203.9+ KB

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Barcarena,BR,75.25,heavy intensity rain,-1.5058,-48.6258,
1,Ulladulla,AU,49.77,broken clouds,-35.3500,150.4667,
2,Dingle,PH,78.12,overcast clouds,10.9995,122.6711,
3,Potsdam,DE,61.34,clear sky,52.3989,13.0657,
4,Fairbanks,US,42.22,broken clouds,64.8378,-147.7164,
5,Lagoa,PT,61.84,scattered clouds,39.0500,-27.9833,
6,Acarau,BR,79.81,moderate rain,-2.8856,-40.1200,
7,Heishan,CN,48.63,clear sky,41.6892,122.1128,
8,Rikitea,PF,76.60,overcast clouds,-23.1203,-134.9692,
9,Hof,DE,56.44,scattered clouds,50.3167,11.9167,

In [12]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
        
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.  
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [14]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Barcarena,BR,75.25,heavy intensity rain,-1.5058,-48.6258,Dos Santos Hotel
1,Ulladulla,AU,49.77,broken clouds,-35.3500,150.4667,Sandpiper Motel
2,Dingle,PH,78.12,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
3,Potsdam,DE,61.34,clear sky,52.3989,13.0657,Dorint Hotel Sanssouci Berlin/Potsdam
4,Fairbanks,US,42.22,broken clouds,64.8378,-147.7164,Westmark Fairbanks Hotel & Conference Center

In [15]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

In [16]:
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Barcarena,BR,75.25,heavy intensity rain,-1.5058,-48.6258,Dos Santos Hotel
1,Ulladulla,AU,49.77,broken clouds,-35.3500,150.4667,Sandpiper Motel
2,Dingle,PH,78.12,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
3,Potsdam,DE,61.34,clear sky,52.3989,13.0657,Dorint Hotel Sanssouci Berlin/Potsdam
4,Fairbanks,US,42.22,broken clouds,64.8378,-147.7164,Westmark Fairbanks Hotel & Conference Center

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [22]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))